config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:new, :show, :create]
  get '/:short_url' => 'urls#re_route'
  root 'urls#new'

end

app/models/url.rb
class Url < ActiveRecord::Base

  validates_uniqueness_of :short_url

  def shorten_url
    # generate a shortest string
    try = true
    while(try) do
      self.short_url = shortest_string
      try = !self.save
    end
  end

  def shortest_string
    # fetch all urls
    urls = Url.all
    # find max char length for short_url
    max_char = urls.max {|u| u.short_url.length}
    # assign 
    max_char = max_char.short_url ? max_char.short_url.length : 1
    short_url = ( ('a'..'z').to_a + (0..9).to_a + ('A'..'Z').to_a ).shuffle.first(max_char).join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  def re_route
    short_url = params[:short_url]
    # TODO: convert non complete urls to actual urls
    url = Url.find_by_short_url(short_url)
    return render json: {error: 'invalid url'} if !url
    redirect_to url.url
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)
    @url.shorten_url
    respond_to do |format|
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, type: 'url' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shorten your urls</h1>

<%= render 'form' %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @url.url %>
</p>

<p>
  <strong>Short url:</strong>
  <a href=<%= request.protocol + request.host_with_port + "/" + @url.short_url %>  > <%= request.protocol + request.host_with_port + "/" + @url.short_url %></a>
</p>